name: github pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Retrieve source code
        uses: actions/checkout@v2

      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3

      - name: Install aspell
        run: sudo apt-get install -y aspell aspell-en

      - name: Check spelling
        run: make lint

      - name: Setup mdbook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.15'

      - name: Build book
        run: make build

      - name: Deploy book
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
          cname: docs.syrac.org
